name: Branch Name

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  check-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Get the branch name
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Validate branch name
        run: |
          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "Branch name 'main' is allowed."
          elif [[ ! "$BRANCH_NAME" =~ ^CBIN-B0-[a-zA-Z]+$ ]]; then
            echo "Branch name '$BRANCH_NAME' does not follow the naming convention."
            echo "Valid format: CBIN-B0-{Yourname}"
            echo "Example: CBIN-B0-JohnDoe"
            exit 1
          else
            echo "Branch name '$BRANCH_NAME' is valid."
          fi
