name: Check Branch Name

on:
  # Trigger the workflow on push and pull requests
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  check-branch-name:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Get branch name
      - name: Get Branch Name
        id: get_branch
        run: |
          echo "Branch ref: $GITHUB_REF"
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          echo "Branch name: $BRANCH_NAME"
          echo "::set-output name=branch_name::$BRANCH_NAME"

      # Step 3: Validate branch name using regex
      - name: Validate Branch Name
        run: |
          BRANCH_NAME=${{ steps.get_branch.outputs.branch_name }}
          echo "Validating branch name: $BRANCH_NAME"
          if [[ ! "$BRANCH_NAME" =~ ^CBIN-B0-[a-zA-Z]+$ ]]; then
            echo "Branch name '$BRANCH_NAME' does not follow the naming convention."
            echo "Valid format: CBIN-B0-{Yourname}"
            echo "Example: CBIN-B0-JohnDoe"
            exit 1
          else
            echo "Branch name '$BRANCH_NAME' follows the naming convention."
          fi
